name: Verify URL's
permissions: 
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
    - name: Setup golang
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
     #uses: actions/setup-go@v2.2.0
      with:
        go-version-file: go.mod
    - name: Install vl
      run: |
        go install github.com/ellisonleao/vl/cmd/vl@main
        echo ${HOME}/go/bin >> $GITHUB_PATH
    # TODO: add caching for this install 
    - name: Check URLs
      run: |
       files_to_check=$( find . -name \*adoc)
       for file in ${files_to_check}; do
        vl "${file}"
       done
